FinalProjectDemo/FinalProjectDemo/Models/Product/MoboFinal.cs
using System;
using System.Collections.Generic;

namespace FinalProjectDemo.Models.Product
{
    public partial class MoboFinal
    {
        public string Brand { get; set; }
        public string Name { get; set; }
        public double RyansPrice { get; set; }
        public double StarPrice { get; set; }
        public string StarLink { get; set; }
        public string RyansLink { get; set; }
        public string PicLink { get; set; }
        public string Description { get; set; }
        public int MoboId { get; set; }
    }
}

FinalProjectDemo/FinalProjectDemo/Controllers/MoboFinalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProjectDemo.Models.Product;

namespace FinalProjectDemo.Controllers
{
    public class MoboFinalController : Controller
    {
        private readonly ProductEntities _context;

        public MoboFinalController(ProductEntities context)
        {
            _context = context;
        }
        [HttpPost]
        public async Task<IActionResult> Index_Search(String searchkey)
        {
            MoboFinal productModel = new MoboFinal();

            var mainboards = from s in _context.MoboFinal select s;
            if (String.IsNullOrEmpty(searchkey))
            {
                ViewBag.showMsg = "Please enter a keyword!";

            }
            else if (!String.IsNullOrEmpty(searchkey))
            {
                ViewBag.showMsg = "";
                mainboards = mainboards.Where(s => s.Name.Contains(searchkey));
                if (mainboards.Count() == 0)
                {
                    ViewBag.notfound = "No Product Found";
                }
                else ViewBag.notfound = "";
            }

            //return View(await _context.DataProcessor.ToListAsync());
            return View(await mainboards.ToListAsync());
        }
        // GET: MoboFinals
        public async Task<IActionResult> Index()
        {
            return View(await _context.MoboFinal.ToListAsync());
        }

        // GET: MoboFinals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moboFinal = await _context.MoboFinal
                .SingleOrDefaultAsync(m => m.MoboId == id);
            if (moboFinal == null)
            {
                return NotFound();
            }

            return View(moboFinal);
        }

        // GET: MoboFinals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MoboFinals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Brand,Name,RyansPrice,StarPrice,StarLink,RyansLink,PicLink,Description,MoboId")] MoboFinal moboFinal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(moboFinal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(moboFinal);
        }

        // GET: MoboFinals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moboFinal = await _context.MoboFinal.SingleOrDefaultAsync(m => m.MoboId == id);
            if (moboFinal == null)
            {
                return NotFound();
            }
            return View(moboFinal);
        }

        // POST: MoboFinals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Brand,Name,RyansPrice,StarPrice,StarLink,RyansLink,PicLink,Description,MoboId")] MoboFinal moboFinal)
        {
            if (id != moboFinal.MoboId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(moboFinal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MoboFinalExists(moboFinal.MoboId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(moboFinal);
        }

        // GET: MoboFinals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moboFinal = await _context.MoboFinal
                .SingleOrDefaultAsync(m => m.MoboId == id);
            if (moboFinal == null)
            {
                return NotFound();
            }

            return View(moboFinal);
        }

        // POST: MoboFinals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var moboFinal = await _context.MoboFinal.SingleOrDefaultAsync(m => m.MoboId == id);
            _context.MoboFinal.Remove(moboFinal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MoboFinalExists(int id)
        {
            return _context.MoboFinal.Any(e => e.MoboId == id);
        }
    }
}

FinalProjectDemo/FinalProjectDemo/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProjectDemo.Models.Product;

namespace FinalProjectDemo.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ProductEntities _context;
        
        public ReviewController(ProductEntities context)
        {
            _context = context;
        }

        // GET: Review
        public async Task<IActionResult> Index()
        {
            return View(await _context.Review.ToListAsync());
        }

        // GET: Review/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .SingleOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Review/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Review/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,ProductName,UserName,ReviewText")] Review review)
        {
            if (ModelState.IsValid)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Review/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review.SingleOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }
            return View(review);
        }

        // POST: Review/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,ProductName,UserName,ReviewText")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Review/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .SingleOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Review/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Review.SingleOrDefaultAsync(m => m.ReviewId == id);
            _context.Review.Remove(review);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
            return _context.Review.Any(e => e.ReviewId == id);
        }
    }
}

FinalProjectDemo/FinalProjectDemo/Views/MoboFinal/Create.cshtml
@model FinalProjectDemo.Models.Product.MoboFinal

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>MoboFinal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RyansPrice" class="control-label"></label>
                <input asp-for="RyansPrice" class="form-control" />
                <span asp-validation-for="RyansPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarPrice" class="control-label"></label>
                <input asp-for="StarPrice" class="form-control" />
                <span asp-validation-for="StarPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarLink" class="control-label"></label>
                <input asp-for="StarLink" class="form-control" />
                <span asp-validation-for="StarLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RyansLink" class="control-label"></label>
                <input asp-for="RyansLink" class="form-control" />
                <span asp-validation-for="RyansLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicLink" class="control-label"></label>
                <input asp-for="PicLink" class="form-control" />
                <span asp-validation-for="PicLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProjectDemo/FinalProjectDemo/Views/MoboFinal/Delete.cshtml
@model FinalProjectDemo.Models.Product.MoboFinal

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MoboFinal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RyansPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RyansPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StarPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StarPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StarLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StarLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RyansLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RyansLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PicLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PicLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MoboId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FinalProjectDemo/FinalProjectDemo/Views/MoboFinal/Details.cshtml
@model FinalProjectDemo.Models.Product.MoboFinal

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <img src="@Model.PicLink" style="margin:20px 20px 20px 0px;" /><br>
    <table class="table-bordered" cellspacing=20>
        <tr>
            <td>Name</td>
            <td> @Html.DisplayFor(model => model.Name)</td>
        </tr>
        <tr>
            <td>Brand</td>
            <td> @Html.DisplayFor(model => model.Brand)</td>
        </tr>


        <tr>
            <td>Price At Ryans Computers</td>
            <td> ৳ @Html.DisplayFor(model => model.RyansPrice)</td>
        </tr>
        <tr>
            <td >Price At Startech Ltd.</td>
            <td> ৳ @Html.DisplayFor(model => model.StarPrice)</td>
        </tr>
        <tr>
            <td colspan="2">
                <button style="background-color:#4e5d6c;width:180px;padding:10px;border:none;" data-toggle="collapse" data-target="#demo">Description&nbsp;&nbsp;<span class="glyphicon glyphicon-plus"></span></button>

                <div id="demo" class="collapse">
                    @Model.Description
                </div>
            </td>

        </tr>
        <tr>
            <td colspan="2">Check out more details at:</td>
        </tr>
        <tr>
            <td><button class="btn-default" onclick="location.href='@Model.StarLink'" type="button">Startech Ltd.</button></td>
            <td><button class="btn-default" onclick="location.href='@Model.RyansLink'" type="button">Ryans Computer</button></td>

        </tr>
    </table><br>
    <button class="btn-default">Add to Wishlist</button>
    <button class="btn-default">@Html.ActionLink("Write a Review", "Create", "Review", null, new { style = "text-decoration:none" })</button>
</div>



<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            } else {
                content.style.display = "block";
            }
        });
    }
</script>

<div class="container">
    <p>Rate this product:</p>
    <div class="rate">

        <input type="radio" id="star5" name="rate" value="5" />
        <label for="star5" title="text">5 stars</label>
        <input type="radio" id="star4" name="rate" value="4" />
        <label for="star4" title="text">4 stars</label>
        <input type="radio" id="star3" name="rate" value="3" />
        <label for="star3" title="text">3 stars</label>
        <input type="radio" id="star2" name="rate" value="2" />
        <label for="star2" title="text">2 stars</label>
        <input type="radio" id="star1" name="rate" value="1" />
        <label for="star1" title="text">1 star</label>
    </div>

</div>

<div>
    @*<a asp-action="Edit" asp-route-id="@Model.MoboId">Edit</a>*@ 
    <span class="glyphicon glyphicon-backward"></span>
    <a asp-action="Index" style="text-decoration:none">Back to Motherboards</a>
</div>

FinalProjectDemo/FinalProjectDemo/Views/MoboFinal/Edit.cshtml
@model FinalProjectDemo.Models.Product.MoboFinal

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>MoboFinal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RyansPrice" class="control-label"></label>
                <input asp-for="RyansPrice" class="form-control" />
                <span asp-validation-for="RyansPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarPrice" class="control-label"></label>
                <input asp-for="StarPrice" class="form-control" />
                <span asp-validation-for="StarPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarLink" class="control-label"></label>
                <input asp-for="StarLink" class="form-control" />
                <span asp-validation-for="StarLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RyansLink" class="control-label"></label>
                <input asp-for="RyansLink" class="form-control" />
                <span asp-validation-for="RyansLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicLink" class="control-label"></label>
                <input asp-for="PicLink" class="form-control" />
                <span asp-validation-for="PicLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="MoboId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProjectDemo/FinalProjectDemo/Views/MoboFinal/Index.cshtml
@model IEnumerable<FinalProjectDemo.Models.Product.MoboFinal>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>


<form asp-controller="MoboFinal" asp-action="Index_Search">

    <input id="my_search_field" placeholder="Enter your keywords!" type="text" name="searchkey">
    &nbsp; &nbsp; &nbsp; <input type="submit" value="Search" />
    <p style="color:orangered;">@ViewBag.showMsg</p>
</form>


<div class="container">
    @foreach (var item in Model)
    {
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">

                    <img src="@item.PicLink" alt="Avatar" style="width:200px;height:200px;">

                </div>
                <div class="flip-card-back">
                    <h5>@item.Name</h5>
                    <p>Startech Price: ৳ @item.StarPrice</p>
                    <p>Ryans Price: ৳ @item.RyansPrice</p>

                    <button class="btn-default"><a asp-action="Details" asp-route-id="@item.MoboId">Details</a> </button>
                </div>
            </div>
        </div>
    }
</div>

FinalProjectDemo/FinalProjectDemo/Views/MoboFinal/Index_Search.cshtml
@model IEnumerable<FinalProjectDemo.Models.Product.MoboFinal>

@{
    ViewData["Title"] = "Index_Search";
}

<h2>Index_Search</h2>

<form asp-controller="MoboFinal" asp-action="Index_Search">

    <input id="my_search_field" placeholder="Enter your keywords!" type="text" name="searchkey">
    &nbsp; &nbsp; &nbsp; <input type="submit" value="Search" />
    <p style="color:orangered;">@ViewBag.showMsg</p>
</form>

@ViewBag.notfound
<div class="container" style="padding:20px;">
    @foreach (var item in Model)
    {
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">

                    <img src="@item.PicLink" alt="Avatar" style="width:200px;height:200px;">

                </div>
                <div class="flip-card-back">
                    <h5>@item.Name</h5>
                    <p>Startech Price: ৳ @item.StarPrice</p>
                    <p>Ryans Price: ৳ @item.RyansPrice</p>

                    <button class="btn-default"><a asp-action="Details" asp-route-id="@item.MoboId">Details</a> </button>
                </div>
            </div>
        </div>
    }
</div>