FinalProjectDemo/FinalProjectDemo/Models/Product/ProcessorFinal.cs
using System;
using System.Collections.Generic;

namespace FinalProjectDemo.Models.Product
{
    public partial class ProcessorFinal
    {
        public string Brand { get; set; }
        public string Name { get; set; }
        public double RyansPrice { get; set; }
        public double StarPrice { get; set; }
        public string StarLink { get; set; }
        public string RyansLink { get; set; }
        public string PicLink { get; set; }
        public string Description { get; set; }
        public int ProId { get; set; }
    }
}

FinalProjectDemo/FinalProjectDemo/Controllers/ProcessorFinalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProjectDemo.Models.Product;

namespace FinalProjectDemo.Controllers
{
    public class ProcessorFinalController : Controller
    {
        private readonly ProductEntities _context;

        public ProcessorFinalController(ProductEntities context)
        {
            _context = context;
        }

        //POST Index action method
        [HttpPost]
        public async Task<IActionResult> IndexAsync(double? lowAmount, double? largeAmount)

        {
            ProcessorFinal productModel = new ProcessorFinal();

            var processors = from s in _context.ProcessorFinal select s;
            if (lowAmount == null || largeAmount == null)
            {
                ViewBag.showMsg = "Please enter a prices!";
            }
            else if (lowAmount != null && largeAmount != null)
            {
                ViewBag.showMsg = "";
                processors = processors.Where(s => s.RyansPrice >= lowAmount && s.RyansPrice <= largeAmount);
            }

            //return View(await _context.DataProcessor.ToListAsync());
            return View(await processors.ToListAsync());



            //var products = _context.ProcessorFinal.Include(c => c.).Include(c => c.SpecialTag)
            //   .Where(c => c.Price >= lowAmount && c.Price <= largeAmount).ToList();
            //if(lowAmount==null ||largeAmount==null)
            //{
            //   products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).ToList();
            //}
            //return View(products);
        }



        [HttpPost]
        public async Task<IActionResult> Index_Search(String searchkey)
        {
            ProcessorFinal productModel = new ProcessorFinal();

            var processors = from s in _context.ProcessorFinal select s;
            if (String.IsNullOrEmpty(searchkey))
            {
                ViewBag.showMsg = "Please enter a keyword!";
                
            }
            else if (!String.IsNullOrEmpty(searchkey))
            {
                ViewBag.showMsg = "";
                processors = processors.Where(s => s.Name.Contains(searchkey));
            }

            //return View(await _context.DataProcessor.ToListAsync());
            return View(await processors.ToListAsync());
        }
        // GET: ProcessorFinal
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProcessorFinal.ToListAsync());
        }

        // GET: ProcessorFinal/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var processorFinal = await _context.ProcessorFinal
                .SingleOrDefaultAsync(m => m.ProId == id);
            if (processorFinal == null)
            {
                return NotFound();
            }

            return View(processorFinal);
        }

        // GET: ProcessorFinal/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProcessorFinal/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Brand,Name,RyansPrice,StarPrice,StarLink,RyansLink,PicLink,Description,ProId")] ProcessorFinal processorFinal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(processorFinal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(processorFinal);
        }

        // GET: ProcessorFinal/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var processorFinal = await _context.ProcessorFinal.SingleOrDefaultAsync(m => m.ProId == id);
            if (processorFinal == null)
            {
                return NotFound();
            }
            return View(processorFinal);
        }

        // POST: ProcessorFinal/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Brand,Name,RyansPrice,StarPrice,StarLink,RyansLink,PicLink,Description,ProId")] ProcessorFinal processorFinal)
        {
            if (id != processorFinal.ProId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(processorFinal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProcessorFinalExists(processorFinal.ProId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(processorFinal);
        }

        // GET: ProcessorFinal/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var processorFinal = await _context.ProcessorFinal
                .SingleOrDefaultAsync(m => m.ProId == id);
            if (processorFinal == null)
            {
                return NotFound();
            }

            return View(processorFinal);
        }

        // POST: ProcessorFinal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var processorFinal = await _context.ProcessorFinal.SingleOrDefaultAsync(m => m.ProId == id);
            _context.ProcessorFinal.Remove(processorFinal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProcessorFinalExists(int id)
        {
            return _context.ProcessorFinal.Any(e => e.ProId == id);
        }
    }
}

FinalProjectDemo/FinalProjectDemo/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProjectDemo.Models.Product;

namespace FinalProjectDemo.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ProductEntities _context;
        
        public ReviewController(ProductEntities context)
        {
            _context = context;
        }

        // GET: Review
        public async Task<IActionResult> Index()
        {
            return View(await _context.Review.ToListAsync());
        }

        // GET: Review/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .SingleOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Review/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Review/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,ProductName,UserName,ReviewText")] Review review)
        {
            if (ModelState.IsValid)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Review/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review.SingleOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }
            return View(review);
        }

        // POST: Review/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,ProductName,UserName,ReviewText")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Review/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .SingleOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Review/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Review.SingleOrDefaultAsync(m => m.ReviewId == id);
            _context.Review.Remove(review);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
            return _context.Review.Any(e => e.ReviewId == id);
        }
    }
}

FinalProjectDemo/FinalProjectDemo/Views/ProcessorFinal/Create.cshtml
@model FinalProjectDemo.Models.Product.ProcessorFinal

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ProcessorFinal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RyansPrice" class="control-label"></label>
                <input asp-for="RyansPrice" class="form-control" />
                <span asp-validation-for="RyansPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarPrice" class="control-label"></label>
                <input asp-for="StarPrice" class="form-control" />
                <span asp-validation-for="StarPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarLink" class="control-label"></label>
                <input asp-for="StarLink" class="form-control" />
                <span asp-validation-for="StarLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RyansLink" class="control-label"></label>
                <input asp-for="RyansLink" class="form-control" />
                <span asp-validation-for="RyansLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicLink" class="control-label"></label>
                <input asp-for="PicLink" class="form-control" />
                <span asp-validation-for="PicLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProjectDemo/FinalProjectDemo/Views/ProcessorFinal/Delete.cshtml
@model FinalProjectDemo.Models.Product.ProcessorFinal

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProcessorFinal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RyansPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RyansPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StarPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StarPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StarLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StarLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RyansLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RyansLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PicLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PicLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FinalProjectDemo/FinalProjectDemo/Views/ProcessorFinal/Details.cshtml
@model FinalProjectDemo.Models.Product.ProcessorFinal

@{
    ViewData["Title"] = "Details";
    ViewBag.name = Model.Name;
}

<div class="container">
    <img src="@Model.PicLink" style="margin:20px 20px 20px 0px;" /><br>
    <table class="table-bordered" cellspacing=20>
        <tr>
            <td>Name</td>
            <td> @Html.DisplayFor(model => model.Name)</td>
            <input hidden />
        </tr>
        <tr>
            <td>Brand</td>
            <td> @Html.DisplayFor(model => model.Brand)</td>
        </tr>

        <tr>
            <td>Price At Ryans Computers</td>
            <td> ৳ @Html.DisplayFor(model => model.RyansPrice)</td>
        </tr>
        <tr>
            <td align="center">Price At Startech Ltd.</td>
            <td> ৳ @Html.DisplayFor(model => model.StarPrice)</td>
        </tr>
        <tr>
            <td colspan="2">
                <button style="background-color:#4e5d6c;width:180px;padding:10px;border:none;" data-toggle="collapse" data-target="#demo">Description&nbsp;&nbsp;<span class="glyphicon glyphicon-plus"></span></button>

                <div id="demo" class="collapse">
                    @Model.Description
                </div>
            </td>

        </tr>
        <tr>
            <td colspan="2">Check out more details at:</td>
        </tr>
        <tr>
            <td><button class="btn-default" onclick="location.href='@Model.StarLink'"  type="button">Startech Ltd.</button></td>
            <td><button class="btn-default" onclick="location.href='@Model.RyansLink'" type="button">Ryans Computer</button></td>

        </tr>
    </table><br>
    <button class="btn-default">Add to Wishlist</button>
    <button class="btn-default">@Html.ActionLink("Write a Review", "Create", "Review", new { product_name=Model.Name}, new { style = "text-decoration:none" })</button>
</div>



<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            } else {
                content.style.display = "block";
            }
        });
    }
</script>

<div class="container">
    <p>Rate this product:</p>
    <div class="rate">

        <input type="radio" id="star5" name="rate" value="5" />
        <label for="star5" title="text">5 stars</label>
        <input type="radio" id="star4" name="rate" value="4" />
        <label for="star4" title="text">4 stars</label>
        <input type="radio" id="star3" name="rate" value="3" />
        <label for="star3" title="text">3 stars</label>
        <input type="radio" id="star2" name="rate" value="2" />
        <label for="star2" title="text">2 stars</label>
        <input type="radio" id="star1" name="rate" value="1" />
        <label for="star1" title="text">1 star</label>
    </div>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.MoboId">Edit</a>*@
    <span class="glyphicon glyphicon-backward"></span>
    <a asp-action="Index" style="text-decoration:none">Back to Processors</a>
</div>
@*<div class="container">
    <h6>Write a review</h6>
    <textarea rows="4" cols="50"> 

</textarea><br>
    <button class="btn-default">@Html.ActionLink("Submit", "Create", "Reviews", null, new { style = "text-decoration:none" })</button>
    <br>
    <br>
</div>*@












































@*<div>
        <h4>ProcessorFinal</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Brand)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Brand)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.RyansPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.RyansPrice)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.StarPrice)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StarPrice)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.StarLink)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StarLink)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.RyansLink)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.RyansLink)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PicLink)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PicLink)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.ProId">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@

FinalProjectDemo/FinalProjectDemo/Views/ProcessorFinal/Edit.cshtml
@model FinalProjectDemo.Models.Product.ProcessorFinal

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ProcessorFinal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RyansPrice" class="control-label"></label>
                <input asp-for="RyansPrice" class="form-control" />
                <span asp-validation-for="RyansPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarPrice" class="control-label"></label>
                <input asp-for="StarPrice" class="form-control" />
                <span asp-validation-for="StarPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarLink" class="control-label"></label>
                <input asp-for="StarLink" class="form-control" />
                <span asp-validation-for="StarLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RyansLink" class="control-label"></label>
                <input asp-for="RyansLink" class="form-control" />
                <span asp-validation-for="RyansLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicLink" class="control-label"></label>
                <input asp-for="PicLink" class="form-control" />
                <span asp-validation-for="PicLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ProId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProjectDemo/FinalProjectDemo/Views/ProcessorFinal/Index.cshtml
@model IEnumerable<FinalProjectDemo.Models.Product.ProcessorFinal>

@{
    ViewData["Title"] = "Processor Prices";
}

<h4>Processor Prices In Startech Ltd. and Ryans Computers</h4>

<p>
    @*<a asp-action="Create">Create New</a>*@

</p>

@*<input class="form-control" placeholder="Enter your keywords!" type="text" name="searchkey">*@

<form asp-controller="ProcessorFinal" asp-action="Index_Search">

    <input id="my_search_field" placeholder="Enter your keywords!" type="text" name="searchkey">
    &nbsp; &nbsp; &nbsp; <input type="submit" value="Search" />
    <p style="color:orangered;">@ViewBag.showMsg</p>

</form>
@*<form method="post">
    <input id="my_search_field" type="text" name="lowAmount">
    <input id="my_search_field" type="text" name="highAmount">
    <input type="submit" value="Search" />
</form>*@

<div class="container" style="padding:20px;">
    @foreach (var item in Model)
    {
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">

                    <img src="@item.PicLink" alt="Avatar" style="width:200px;height:200px;">

                </div>
                <div class="flip-card-back">
                    <h5>@item.Name</h5>
                    <p>Startech Price: ৳ @item.StarPrice</p>
                    <p>Ryans Price: ৳ @item.RyansPrice</p>

                    <button class="btn-default"><a asp-action="Details" asp-route-id="@item.ProId">Details</a> </button>
                </div>
            </div>
        </div>
    }
</div>


@*trying something different*@



@*<table class="table">
        <thead>
            <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Brand)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.RyansPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StarPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StarLink)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.RyansLink)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PicLink)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Brand)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RyansPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StarPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StarLink)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RyansLink)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PicLink)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ProId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ProId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProId">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>*@

FinalProjectDemo/FinalProjectDemo/Views/ProcessorFinal/Index_Search.cshtml
@model IEnumerable<FinalProjectDemo.Models.Product.ProcessorFinal>

@{
    ViewData["Title"] = "Index_Search";
}

<h4>Processor Prices In Startech Ltd. and Ryans Computers</h4>
<form asp-controller="ProcessorFinal" asp-action="Index_Search">

    <input id="my_search_field" placeholder="Enter your keywords!" type="text" name="searchkey">
    &nbsp; &nbsp; &nbsp; <input type="submit" value="Search" />
    <p style="color:orangered;">@ViewBag.showMsg</p>
</form>
@ViewBag.notfound
<div class="container" style="padding:20px;">
    @foreach (var item in Model)
    {
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">

                    <img src="@item.PicLink" alt="Avatar" style="width:200px;height:200px;">

                </div>
                <div class="flip-card-back">
                    <h5>@item.Name</h5>
                    <p>Startech Price: BDT @item.StarPrice</p>
                    <p>Ryans Price: BDT @item.RyansPrice</p>

                    <button class="btn-default"><a asp-action="Details" asp-route-id="@item.ProId">Details</a> </button>
                </div>
            </div>
        </div>
    }
</div>